### ISSUE TITLE
Problem about indicators

### ISSUE THREAD

**Issue by e20916** [aduryagin/technical-indicators#1]
Hi, i download your library via npm and I copy the example of RSI code but the output value is not the same as expected. I use node.js.Can you look at it?

const TA = require('@aduryagin/technical-indicators');
	
		
const candles = [
    { time: 0, close: 12.2 },
    { time: 1, close: 12.4 },
    { time: 2, close: 13 }
  ];
  const period = 1;
  const rsi = TA.RSI({ candles, period });
  console.log(rsi);
  /*
    {
      result: [
        { time: 1, value: 100, candle: { time: 1, close: 12.4 } },
        { time: 2, value: 100, candle: { time: 2, close: 13 } }
      ],
      update: [Function: update]
    }
  */
  const rsiResult = rsi.update({ time: 2, close: 1 });
  console.log(rsiResult);

Output:

{ result: [Function: result], update: [Function: update] }
{ time: 2, value: 0, candle: { time: 2, close: 1 } }

Pic: 
![image](https://user-images.githubusercontent.com/73392790/110816225-34f65500-829c-11eb-9a84-f95c3ce0387d.png)

Output pic:
![image](https://user-images.githubusercontent.com/73392790/110816297-463f6180-829c-11eb-8aad-7d7216b12655.png)

**Comment by aduryagin** [comment]
Hi, you got the correct result for this parameters (period: 1, candles: [{ time: 0, close: 12.2 }, ...]).

After executing TA.RSI you get an object with **result** (here placed calculated rsi) and **update** (you can execute this function on every candle update. this function will return latest calculated rsi value)
